# Generated by Django 4.2.7 on 2026-06-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='company',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
