# Generated by Codex on 2026-07-16

from datetime import timedelta

from django.db import migrations, models


def backfill_follow_up_due_dates(apps, schema_editor):
    JobApplication = apps.get_model('applications', 'JobApplication')
    for application in JobApplication.objects.all():
        if application.status == 'Rejected':
            continue

        application.follow_up_due_date = application.application_date + timedelta(days=7)
        application.follow_up_interval_days = 7
        application.save(update_fields=['follow_up_due_date', 'follow_up_interval_days'])


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_jobapplication_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='follow_up_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='follow_up_interval_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='last_follow_up_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_follow_up_due_dates, migrations.RunPython.noop),
    ]
