# Generated by Codex on 2026-07-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_jobapplication_follow_up_schedule'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notifications',
                to='applications.jobapplication',
            ),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(
                choices=[
                    ('follow_up', 'Follow-up Reminder'),
                    ('interview', 'Interview Update'),
                    ('deadline', 'Deadline Update'),
                    ('general', 'General'),
                ],
                default='general',
                max_length=20,
            ),
        ),
    ]
