# Generated by Django 5.2.14 on 2026-07-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='document_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('other', 'Other')], max_length=20),
        ),
    ]
